config/routes.rb
Onapp::Application.routes.draw do

  devise_for :users
  resources :tickets
  resources :customer_tickets
  authenticated :user do
    root to: "tickets#index", as: "authenticated_user"
  end
  root 'customer_tickets#new'
end

app/models/response.rb
class Response < ActiveRecord::Base
  belongs_to :ticket

  validates :text, presence: true

  before_save :set_owner
  after_create :notify_customer

  private

  def set_owner
    self.user_id = ticket.user_id
  end

  def notify_customer
    UserMailer.ticket(ticket, 'Someone has edited the ticket', 'updated', self).deliver
  end
end

app/models/ticket.rb
# == Schema Information
#
# Table name: tickets
#
#  id         :integer          not null, primary key
#  status     :string(255)
#  name       :string(255)
#  email      :string(255)
#  subject    :string(255)
#  body       :text
#  uid        :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Ticket < ActiveRecord::Base
  searchkick

  include PublicActivity::Model
  tracked

  STATUSES = [
    WAIT_STAFF = 'waiting_staff'.freeze,
    WAIT_CUSTOMER = 'waiting_customer'.freeze,
    HOLD = 'hold'.freeze,
    CANCELLED = 'cancelled'.freeze,
    COMPLETED = 'completed'.freeze
    ]

  STATUSES.each do |status|
    scope status, -> {where(status: status)}
  end
  scope :closed, -> {where("status = ? OR status = ?", CANCELLED, COMPLETED)}

  belongs_to :user
  has_many :responses, dependent: :destroy

  accepts_nested_attributes_for :responses, allow_destroy: true, reject_if: proc { |attrs| attrs['text'].blank? }

  before_create :set_status, :set_uid
  after_update :notify_customer

  with_options presence: true do |this|
    this.validates :name, length: {maximum: 255}
    this.validates :email, format: {with: Devise.email_regexp}
    this.validates :subject
    this.validates :body
  end

  private

  def set_status
    self.status = WAIT_STAFF
  end

  def set_uid
    StringRandom.random
  end

  def notify_customer
    UserMailer.ticket(self, 'Someone has edited the ticket', 'updated').deliver if status_changed? or user_id_changed?
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime
#  updated_at             :datetime
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tickets
  has_many :responses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/customer_tickets_controller.rb
class CustomerTicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]

  def edit; end

  def show; end

  def new
    @ticket = Ticket.new
  end

  def create
    @ticket = Ticket.new(ticket_params)
    if @ticket.save
      UserMailer.ticket(@ticket, t('activity.ticket.create'), 'created').deliver
      redirect_to [:new, :customer_ticket], notice: 'Ticket was successfully created.'
    else
      render action: 'new'
    end
  end

  private
    def set_ticket
      @ticket = Ticket.find(params[:id])
      @activities = PublicActivity::Activity.where(trackable: @ticket)
    end

    def ticket_params
      params.require(:ticket).permit(:name, :email, :subject, :body)
    end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]

  def index
    status = params[:status] if Ticket::STATUSES.include?(params[:status])
    if status
      tickets = Ticket.send(status)
    else
      tickets = Ticket.all
    end
    @tickets = params[:query].present? ? tickets.search(params[:query], page: params[:page]) : tickets
  end

  def show; end

  def new
    @ticket = Ticket.new
  end

  def edit; end

  def create
    @ticket = Ticket.new(ticket_params)

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
        format.json { render action: 'show', status: :created, location: @ticket }
      else
        format.html { render action: 'new' }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url }
      format.json { head :no_content }
    end
  end

  private
    def set_ticket
      @ticket = Ticket.find(params[:id])
      @activities = PublicActivity::Activity.where(trackable: @ticket)
    end

    def ticket_params
      params.require(:ticket).permit(:name, :user_id, :status, :email, :subject, :body, responses_attributes: [:id, :text, :_destroy])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def nav_link(text, status)
    content_tag :li, class: "#{'active' if params[:status] == status}" do
      link_to text, tickets_path(status: status)
    end
  end
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/customer_tickets/_form.html.haml
= form_for @ticket, url: customer_tickets_path, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :name, :class => 'control-label'
    .controls
      = f.text_field :name, :class => 'text_field'
  .control-group
    = f.label :email, :class => 'control-label'
    .controls
      = f.text_field :email, :class => 'text_field'
  .control-group
    = f.label :subject, :class => 'control-label'
    .controls
      = f.text_field :subject, :class => 'text_field'
  .control-group
    = f.label :body, :class => 'control-label'
    .controls
      = f.text_field :body, :class => 'text_field'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'

app/views/customer_tickets/new.html.haml
- model_class = Ticket
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/customer_tickets/show.html.haml
- model_class = Ticket
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:status) + ':'
  %br
  = @ticket.status
%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @ticket.name
%p
  %strong= model_class.human_attribute_name(:email) + ':'
  %br
  = @ticket.email
%p
  %strong= model_class.human_attribute_name(:subject) + ':'
  %br
  = @ticket.subject
%p
  %strong= model_class.human_attribute_name(:body) + ':'
  %br
  = @ticket.body

.activity
  = render_activities(@activities)

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Onapp"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'


  %body
    .navbar.navbar-fluid-top
      .navbar-inner
        .container-fluid
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand(href="/") Onapp
          .container.nav-collapse
            %ul.nav
              - if signed_in?
                %li= link_to "New Ticket", new_customer_ticket_path
                %li= link_to "Tickets", tickets_path
                %li= link_to "Sign Out", destroy_user_session_path, method: :delete
              - else
                %li= link_to "Sign In", new_user_session_path
            - if signed_in?
              = form_tag tickets_path, class: "form-inline", method: :get do
                = text_field_tag :query, params[:query], class: "form-control"
                = submit_tag "Search", class: "btn btn-primary"

    .container-fluid

      .row-fluid
        .span3
          - if signed_in?
            .well.sidebar-nav
              %ul.nav.nav-list
                %li.nav-header Tickets
                = nav_link "New unassigned", Ticket::WAIT_STAFF
                = nav_link "Open", Ticket::WAIT_CUSTOMER
                = nav_link "On hold", Ticket::HOLD
                = nav_link "Closed", 'closed'
        .span9
          = bootstrap_flash
          = yield
    
      %footer
        %p &copy; Company 2013
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"

app/views/public_activity/ticket/_create.html.haml
= t('activity.ticket.create')
at
= l activity.created_at
- if activity.trackable
  = link_to activity.trackable.name, activity.trackable
- else
  = t('activity.ticket.destroyed')
%br

app/views/public_activity/ticket/_update.html.haml
= t('activity.ticket.update')
= link_to activity.trackable.name, activity.trackable
%br

app/views/tickets/_form.html.haml
= nested_form_for @ticket, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :owner, :class => 'control-label'
    .controls
      = f.select :user_id, User.all.collect {|p| [ p.email, p.id ] }
  .control-group
    = f.label :status, :class => 'control-label'
    .controls
      = f.select :status, Ticket::STATUSES
  .control-group
    = f.label :name, :class => 'control-label'
    .controls
      = f.text_field :name, :class => 'text_field'
  .control-group
    = f.label :email, :class => 'control-label'
    .controls
      = f.text_field :email, :class => 'text_field'
  .control-group
    = f.label :subject, :class => 'control-label'
    .controls
      = f.text_field :subject, :class => 'text_field'
  .control-group
    = f.label :body, :class => 'control-label'
    .controls
      = f.text_field :body, :class => 'text_field'
  .control-group
    = f.fields_for :responses do |r_f|
      = r_f.text_field :text
      = r_f.link_to_remove "Remove this response"
    = f.link_to_add "Add a response", :responses
  .control-group
    = f.label :uid, :class => 'control-label'
    .controls
      = f.text_field :uid, :class => 'text_field'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), tickets_path, :class => 'btn'

app/views/tickets/edit.html.haml
- model_class = Ticket
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/tickets/index.html.haml
- model_class = Ticket
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:status)
      %th= model_class.human_attribute_name(:owner)
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:email)
      %th= model_class.human_attribute_name(:subject)
      %th= model_class.human_attribute_name(:body)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @tickets.each do |ticket|
      %tr
        %td= link_to ticket.id, ticket_path(ticket)
        %td= ticket.status
        %td= ticket.user.try(:email)
        %td= ticket.name
        %td= ticket.email
        %td= truncate ticket.subject, length: 10
        %td= truncate ticket.body, length: 10
        %td=l ticket.created_at, format: :short
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_ticket_path(ticket), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), ticket_path(ticket), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_ticket_path, :class => 'btn btn-primary'

app/views/tickets/new.html.haml
- model_class = Ticket
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/tickets/show.html.haml
- model_class = Ticket
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:status) + ':'
  %br
  = @ticket.status
%p
  %strong= model_class.human_attribute_name(:owner) + ':'
  %br
  = @ticket.user.try(:email)
%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @ticket.name
%p
  %strong= model_class.human_attribute_name(:email) + ':'
  %br
  = @ticket.email
%p
  %strong= model_class.human_attribute_name(:subject) + ':'
  %br
  = @ticket.subject
%p
  %strong= model_class.human_attribute_name(:body) + ':'
  %br
  = @ticket.body
%p
  %strong= model_class.human_attribute_name(:uid) + ':'
  %br
  = @ticket.uid

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), tickets_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_ticket_path(@ticket), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), ticket_path(@ticket), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'
.activity
  = render_activities(@activities)